### ISSUE TITLE
"Install from update site" not possible after registering

### ISSUE THREAD

**Issue by BeckmaR** [Yakindu/statecharts#1005]
This button ->
![unbenannt](https://cloud.githubusercontent.com/assets/15799654/19090238/cc484826-8a7d-11e6-9f8e-cf3089111a63.png)
does nothing, it only reloads the site with a new link. Tested on linux with firefox and chrome.

**Comment by andreasmuelder** [comment]
@RainerKlute can you reproduce this on Linux?

**Comment by RainerKlute** [comment]
Confirmed. Tested with current versions of Firefox, Chromium, and Konqueror.

(It also turned out that the registration form on https://info.itemis.com/download-yakindu-statechart-tools is not displayed when the Privacy Badger https://www.eff.org/de/privacybadger is used. The Privacy Badger detects six trackers on that webpage and deactivates the five Hubspot trackers.)

**Comment by andreasmuelder** [comment]
Reported as fixed from our webmaster
