### ISSUE TITLE
Coverage Feature: refactor "copy-paste" switch statements as private functions

### ISSUE THREAD

**Issue by yuecelm** [Yakindu/statecharts#103]
in SIL projects its important that the source code coverage is as high as possible (resp. uncovered source code need to be well reasoned). With the help of googletest and gcc/gcov/lcov I found out that the following 2 locations with the C++ code generator were uncovered:
 - switch default cases: can be well reasoned why its not reached
 - in react_[state-x] functions only the switch case state-x is covered, other switch cases remains uncovered:

![image](https://cloud.githubusercontent.com/assets/12153500/7371034/84a159b6-edbe-11e4-82ce-a00b83dd6f0c.png)
 
In order to improve the code coverage I suggest here to wrap the complete switch statement into a private function and the react functions will call the fitting private switch function. With this modification only the switch default cases will remain uncovered...

**Comment by terfloth** [comment]
The generator can be configured to avoid this kind of redundancy. Add the FunctionInlining feature to your sgen generator model:

```
		feature FunctionInlining {
			inlineReactions = false
			inlineEntryActions = false
			inlineExitActions = false
			inlineEnterSequences = false
			inlineExitSequences = false
			inlineChoices = false
			inlineEnterRegion = false
			inlineExitRegion = false
			inlineEntries = false
		}
```
See issue #84 for more information . Since i assume this will solve your problem and #84 is a related issue i will close this one. If this does not solve your problem than reopen it or report another issue.
