### ISSUE TITLE
add validation rule "outgoing events are not allowed as transition triggers"

### ISSUE THREAD

**Issue by tangele** [Yakindu/statecharts#2205]
An usability Test revealed that an user misunderstood the meaning of the `in` / `out` events, therefore he used an outgoing event as transition trigger. The simulation didn't work, but no error was given to explain the reason - therefore, the user was confused and didn't know how to fix it.

**Comment by terfloth** [comment]
Check impact.

**Comment by terfloth** [comment]
Out events are visible and can be used as triggers if they were raised in the same run cycle before. Like internal events cycle based execution they are just visible "downstream". We have to maintain backwards compatibility for this case. So this issue is invalid. 

Nevertheless issue #2434 and #2435 was derived from this issue.
