### ISSUE TITLE
When leaving a region through an exit point, the region exit sequence should not get executed (dead code).

### ISSUE THREAD

**Issue by nyssen** [Yakindu/statecharts#227]
In case a region is exited through an exit point, (at least) the c code generator generates the execution of the region exit sequence (which is a switch case that would execute the exit actions of the respective nested state), which is dead code (because there is no active state in the region). We should optimize the generator to omit the region exit sequence when leaving the region through an exit point.

Consider the following state machine:

[default.sct.txt](https://github.com/Yakindu/statecharts/files/54201/default.sct.txt)
[default.sgen.txt](https://github.com/Yakindu/statecharts/files/54202/default.sgen.txt)

Within the generated reaction of the nested region's CS2 state, 

> /\* The reactions of state CS2. _/
> static void default_react_main_region_CompositeWithExit_nested_region_CS2(Default_ handle) {
>   /\* The reactions of state CS2. _/
>   /_ Default exit sequence for state CS2 _/
>   handle->stateConfVector[0] = Default_last_state;
>   handle->stateConfVectorPosition = 0;
>   /_ Exit action for state 'CS2'. */
>   handle->internal.value += 1;
>   default_react_main_region_CompositeWithExit_nested_region_exitPoint(handle);
> }

the call to `default_react_main_region_CompositeWithExit_nested_region_exitPoint(handle)` will lead to `default_exseq_main_region_CompositeWithExit_nested_region(handle)`, which is superfluous.

**Comment by terfloth** [comment]
This effect is escpecially visible for inlined code that is created generically from the basic sequence structure. Here a sequence that performs the exit of a composite state is used. This will be called whenever the composite state will be left. Es it can be called 'from different sibling regions' it simply tests every region if something has to be done. In the case of inlining this sequence its content will be inlined in each exit context and for each of those contexts there is one path that cannot be executed as it refers to the already inactive region. 

This issue is not easy to fix as inlining can not discover dead branches that are created by the expansion mechanism.

As there is a major refactoring ongoing (#2579) that addresses eliminating redundant and dead code this issue will be closed.
