### ISSUE TITLE
Only generate includes when used

### ISSUE THREAD

**Issue by andreasmuelder** [Yakindu/statecharts#2388]
for C and C++, the headers 'stdlib.h' and 'string.h' are generated as includes into the C Module:
```
#include <stdlib.h>
#include <string.h>
```

We should only generate those includes if they are required

**Comment by andreasmuelder** [comment]
Is it sufficient to always include the headers when the String / Char type is used in the statechart?

**Comment by terfloth** [comment]
* <string.h> is just used if string compare is used in expressions. 
* <stdlib.h> seems not to be used. The initial assumption was that malloc & co is required for string concatenation. But this is not supported (type system constraint)

So the issue should be fixed in the following way for the C and C++ code generators independently:

* include <string.h> only if a string compare is required.
* check if there is somewhere (also C domain) a need for stdlib. If not remove it completely

**Comment by terfloth** [comment]
@BeckmaR - please fix this issue.
