### ISSUE TITLE
Add support for generating tracing callbacks (in C generator).

### ISSUE THREAD

**Issue by nyssen** [Yakindu/statecharts#266]
We should create a code generator feature that enables creation of callbacks, via which entering and exiting of states an be traced. The callbacks could be generated into the 'Required' header. It should pass a respective state identifier.

**Comment by nyssen** [comment]
Merged enhancement into master. Resolving as fixed.

**Comment by terfloth** [comment]
Reopened since the generated code is not compilable and complete.

In detail there are the following problems:
1. The required header declares the callback function prototypes "extern void stateEntered(const SCTStates state);" and "extern void stateEntered(const SCTStates state);" wich uses the undefined type SCTStates
2. The callback function names are not scoped by a prefix as other callback functions but should be.
3. It is not possible to distinguish different state machine instances in the callback implementation as the handle is not provided as parameter.

**Comment by terfloth** [comment]
We should define test cases for this feature. At least we require an entry for the manual test plan.

**Comment by nyssen** [comment]
I will take a look into it.

**Comment by nyssen** [comment]
I fixed the issues you named. What remains is to define test cases for this functionality.
