### ISSUE TITLE
add quickfix to create a new event when "Trigger is no event" && "Could not find declaration of 'a' ""

### ISSUE THREAD

**Issue by tangele** [Yakindu/statecharts#2700]
ref #2449

**Comment by tkutz** [comment]
This is fixed with PR https://github.com/Yakindu/statecharts/pull/2738 by adding two quickfixes:
(1) For missing **trigger** event, a quickfix adds an **in event** and if needed the surrounding interface and (2) for missing **raise** events, a quickfix adds an **out event** and if needed the surrounding interface.
