### ISSUE TITLE
3.5.3: inconsistent features of inEventQueue among different generatormodels

### ISSUE THREAD

**Issue by tangele** [Yakindu/statecharts#2727]
ref https://github.com/Yakindu/statecharts/pull/2724
version: https://github.com/Yakindu/statecharts/commit/0a9647ebb4ca844c4aca42e1734ba30b71b2ef99

release notes say:
`To enable it, set the inEventQueue option of the GenerationOptions feature to true. `

For `c`:

```
		feature GeneratorOptions {
			inEventQueue = true
		}
```

For `c++'
```
		feature GeneratorOptions {
			inEventQueue = true
		}
```

For `java`:
```

		feature GeneralFeatures {
			inEventQueue = true
		}
```

**Comment by tkutz** [comment]
1. The documentation is correct for Java and C++, but seems to be missing for C.
2. The release notes are also correct (now).
3. In Java, all kinds of options are grouped in `GeneralFeatures`, so for me it makes sense to put `inEventQueue` there.
4. In C++, it is called `GeneratorOptions`, so that is the reason why it is also called so in C.

My suggestion is to close this issue and create two different one: (1) update documentation for C code generation; (2) cleanup generator options when jumping to version 4.
