### ISSUE TITLE
Dead transition not marked as such

### ISSUE THREAD

**Issue by Mazesch** [Yakindu/statecharts#3010]
If there are two timed transitions with different times, the longer one will never be taken, since the first one is always faster.
But the slower transition is not marked as `dead`.

![Unreachable](https://user-images.githubusercontent.com/53564458/74933141-ac341f00-53e3-11ea-9e49-3eea5a716762.PNG)

**Comment by tkutz** [comment]
Actually, this is even more tricky. Consider the case in which the transition prios are swapped (the longer time trigger has prio 1); then in the CycleBased case, with cycles higher than 100ms, both triggers would be valid in the same RTC step, and because of the prio, the 101ms trigger would be taken instead of the 100ms one.

**Comment by terfloth** [comment]
Requires model checking ...
