### ISSUE TITLE
Ambiguous license information and impress and the future of YAKINDU SCT

### ISSUE THREAD

**Issue by stmork** [Yakindu/statecharts#311]
We are planning to use a long term product for state machines - may be YAKINDU SCT professional. But there is no information about the license of YAKINDU SCT concerning the tool itself and the generated code nor any information who owns SCT. The domain statecharts.org is owned by Andreas Mülder but the impress shows itemis. The source code is hosted by Google Code and the bug tracker at github. This seems to be very confusing. We got to know that Xtext core developer left itemis so we need to know something about the future of SCT. We don't talk about some years we talk about of at least 10 years. Do you have information about these issues?

**Comment by terfloth** [comment]
The source code is not hosted on Google Code anymore since Google shuts down that service. It is available on github since April 2015.  

All open source code is provided under EPL license as stated on:  https://github.com/Yakindu/statecharts and the eclipse feature legal info. There is no ambiguity regarding the open source part. YAKINDU SCT does not impose any license constraint on the generated code. The user free to do whatever he wants. All code generators provide a configuration feature 'LicenceHeader' that allows the user to specify his individual license text that will be placed in the generated code.

As YAKINDU SCT is open source anyone may use, clone, and fork the source code. The vast majority of contributions are made by itemis employees. There are also contributions by others (like the upcoming C# generator). All infrastructure except for github and the Trevis CI build are provided by itemis.

itemis provides commercial services including long term support for YAKINDU SCT.  itemis will also provide commercial extensions (Pro Edition) to the open source core . These extensions will be provided under a commercial license. These extensions won't impact the well known functionality of the open source part.
