### ISSUE TITLE
Simulation cannot be run as the value of an event can be set just the first time.

### ISSUE THREAD

**Issue by arelic** [Yakindu/statecharts#329]
Hello,

During simulation run the "value" of each event can be set just the first time until the event is the first time raised. 

After that the "value" cell in the table remains disabled and the new value for the same event cannot be entered any more.
![image](https://cloud.githubusercontent.com/assets/16915740/12717144/28613aaa-c8e6-11e5-9215-cd3948e6f67e.png)

Best regards,
Alex

**Comment by andreasmuelder** [comment]
The type of the cell editor (string, real, integer, boolean) is selected by its java runtime type. When an event is raised, the value of the event isunset( = null) and the runtime type information is gone. This should be refactored that the type from the declaration is used to identify the right cell editor instead of the type of the runtime value.

**Comment by andreasmuelder** [comment]
Fixed
