### ISSUE TITLE
Local transition behaves like external transition

### ISSUE THREAD

**Issue by danlhenry** [Yakindu/statecharts#518]
UML specifies that a local transition does not cause exit from the main source state if the main target state is a substate of the main source.  Also, a local state transition does not cause exit and reentry to the main target state if the main target state is a superstate of the main source state.

For example, referring to UML 2.5's Figures 14.34 and 14.35, Yakindu SCT 2.5 emits the same code for the transition to s1 for both types of transitions; that is, local implemented as external.

**Comment by terfloth** [comment]
There is no distinction between local and external transitions in SCT as in UML. Base abstraction in SCT are reactions. Reactions may be local reactions that you may specify textually in the text compartments of states or the statechart. These local reactions cover what UML tries to achieve with internal transitions. In SCT transitions are also reactions that additionally perform a state transition. This always implies exit and entry of the source and target state. As we also consider using routing properties to define semantic variants as bas style we won't support this. So as the SCT behavior is well defined and there is no concept of 'UML local transition' in SCT this issue is invalid and will be closed. 

Nevertheless as supporting the case that UML local transitions address is valid i opened issue #519 . An implementation would apply a noter notation for transitions or the use of the concept of mediators.
